on:
  workflow_dispatch:
  push:
    branches: main
  pull_request:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'

      - name: Install R packages
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Install LaTeX (TinyTeX)
        uses: r-lib/actions/setup-tinytex@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render book in pdf
        run: |
          quarto render --to pdf --output developer_book.pdf

      - name: Move pdf to data folder
        run: |
          mv "_site/developer_book.pdf" "developer_book.pdf"

      - name: Render book in html
        run: |
          quarto render --to html

      - name: Move pdf back to _site folder
        run: |
          mv "developer_book.pdf" "_site/developer_book.pdf"

      # Publish HTML and pdf from _site to GitHub Pages
      - name: Publish to GitHub Pages
        if: github.event_name == 'push'
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

